### Create a trip
POST http://localhost:9001/trips
Content-Type: application/json

{
  "departure": "2022-10-3",
  "origin": {
    "latitude": 50.849386,
    "longitude": 4.451007
  },
  "destination": {
    "latitude": 50.84937,
    "longitude": 4.451
  },
  "driverId": 12,
  "availableSeat": 1
}

### Get all trips
GET http://localhost:9001/trips

### Get all trips with this date
GET http://localhost:9001/trips?departure=2022-10-3

### Get all trips with this origin coordinates
GET http://localhost:9001/trips?originLat=50.849386&originLon=4.451007

### Get all trips with this destination coordinates
GET http://localhost:9001/trips?destinationLat=50.84937&destinationLon=4.451

### Get One trip
GET http://localhost:9001/trips/1

### Delete a trip
DELETE http://localhost:9001/trips/2

### Get All trips from a driver
GET http://localhost:9001/trips/driver/12

### Get all trips from a driver with this date
GET http://localhost:9001/trips/driver/12?departure_date=2022-10-25

### Get all trips from a driver with this origin coordinates
GET http://localhost:9001/trips/driver/12?originLat=50.849386&originLon=4.451007

### Get all trips from a driver with this destination coordinates
GET http://localhost:9001/trips/driver/12?destinationLat=50.84937&destinationLon=4.451

### Detete a list trips from a driver
DELETE http://localhost:9001/trips/driver/12

