### GET PASSENGER STATUS - 404
GET http://localhost:9003/passengers/1/1

### CREATE PASSENGER - 201
POST http://localhost:9003/passengers/1/1

### GET PASSENGER STATUS - 200 (pending)
GET http://localhost:9003/passengers/1/1

### CREATE PASSENGER WITH SAME FKs - 400
POST http://localhost:9003/passengers/1/1

### UPDATE PASSENGER STATUS WITH NOT KNOWN STATUS - 400
PUT http://localhost:9003/passengers/1/1?status=notknownstatus

### UPDATE PASSENGER STATUS WITH KNOWN STATUS - 200
PUT http://localhost:9003/passengers/1/1?status=accepted

### GET PASSENGER STATUS - 200 (accepted)
GET http://localhost:9003/passengers/1/1

### UPDATE PASSENGER STATUS WITH KNOWN STATUS BUT ALREADY ACCEPTED - 400
PUT http://localhost:9003/passengers/1/1?status=refused

### GET TRIPS OF A USER - 200 - one trip in accepted array
GET http://localhost:9003/passengers/user/1

### GET PASSENGERS OF A TRIP - 200 - user on accepted array
GET http://localhost:9003/passengers/trip/1

### DELETE TRIPS OF A USER - 200
DELETE http://localhost:9003/passengers/user/1

### DELETE A USER FROM A TRIP
DELETE http://localhost:9003/passengers/1/1

### GET PASSENGERS OF A TRIP - 200 - empty arrays
GET http://localhost:9003/passengers/trip/1

### GET TRIPS OF A USER - 200 - empty arrays
GET http://localhost:9003/passengers/user/1
