### CREATE NOTIFICATION
POST http://localhost:9006/notifications
Content-Type: application/json

{
  "userId": 1,
  "tripId": 1,
  "date": "2012-02-15",
  "notificationText": "Salute"
}

### GET NOTIFICATION
GET http://localhost:9006/notifications/1

### DELETE NOTIFICATIONS
DELETE http://localhost:9006/notifications/1