### Create user
POST http://localhost:8080/users/Seb
Content-Type: application/json

{
  "pseudo": "Seb",
  "firstname": "Sébastien",
  "lastname": "Strebelle",
  "password": "notsaying"
}

### Connect user
POST http://localhost:8080/auth
Content-Type: application/json

{
  "pseudo": "Seb",
  "password": "notsaying"
}

> {% client.global.set("token", response.body) %}

### Delete user
DELETE http://localhost:8080/users/Seb
Authorization: {{token}}
