### Create user
POST http://localhost:8080/users/Seb
Content-Type: application/json

{
  "pseudo": "Seb",
  "firstname": "Sébastien",
  "lastname": "Strebelle",
  "password": "notsaying"
}

### Connect user
POST http://localhost:8080/auth
Content-Type: application/json

{
  "pseudo": "Seb",
  "password": "notsaying"
}

> {% client.global.set("token", response.body) %}

### Create video
POST http://localhost:8080/videos/test
Content-Type: application/json
Authorization: {{token}}

{
  "hash": "test",
  "name": "myvid",
  "author": "Seb",
  "creationYear": 2022,
  "duration": 420,
  "url": "nope"
}

### Read user videos
GET http://localhost:8080/users/Seb/videos

### Delete user
DELETE http://localhost:8080/users/Seb
Authorization: {{token}}
