### Create credentials
POST http://localhost:9004/authentication/Cat4Life
Content-Type: application/json

{
  "pseudo": "Cat4Life",
  "password": "azerty"
}

### Update credentials
PUT http://localhost:9004/authentication/Cat4Life
Content-Type: application/json

{
  "pseudo": "Cat4Life",
  "password": "password123"
}

### Delete credentials
DELETE http://localhost:9004/authentication/Cat4Life

### Connect user
POST http://localhost:9004/authentication/connect
Content-Type: application/json

{
  "pseudo": "Cat4Life",
  "password": "azerty"
}

### Verify token
POST http://localhost:9004/authentication/verify
Content-Type: application/json

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJhdXRoMCIsInBzZXVkbyI6IkNhdDRMaWZlIn0.LqfooEI-I9VTBo-isjm812ttnIPagMCwdhRkW5ngn0_tlLX86LRoxahgskmgIeWDbm4Mu3y3D8Qbhq_71hNQTA